---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-spring    
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app: spring
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: pod-spring
      labels:
        app: spring
    spec:
      containers:
        - name: pod-container
          image: jya94/spring-petclinic:latest
          ports:
            - containerPort: 8080
