apiVersion: v1
kind: Service
metadata:
  name: svc-spring    
spec:    
  selector:
    app: spring
  ports:
    - name: svc-port
      type: NodePort
      port: 8080
      targetPort: 8080
      nodePort: 31000
